<?xml version="1.0" encoding="utf-8"?><Database Name="ExampleDatabase" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Ahmed-Refaat;Initial Catalog=ExampleDatabase;Integrated Security=True" SettingsObjectName="Grouping.Properties.Settings" SettingsPropertyName="ExampleDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Grouping_Db" Member="Grouping_Dbs">
    <Type Name="Grouping_Db">
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>